//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQTools.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IQTools.Assets.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose  an Access Database.
        /// </summary>
        internal static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Backup Procedure Is Complete.
        /// </summary>
        internal static string BackupComplete {
            get {
                return ResourceManager.GetString("BackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all the logs?.
        /// </summary>
        internal static string ClearLogs {
            get {
                return ResourceManager.GetString("ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQTools Error.
        /// </summary>
        internal static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        internal static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQTools .
        /// </summary>
        internal static string InfoHeader {
            get {
                return ResourceManager.GetString("InfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQTools will be updated once you have internet connection.
        /// </summary>
        internal static string InternetConnectivity {
            get {
                return ResourceManager.GetString("InternetConnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid password for this account.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current settings are incorrect. Please correct them before logging in.
        /// </summary>
        internal static string InvalidSettings {
            get {
                return ResourceManager.GetString("InvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UserName or Password provided is incorrect. Please try again..
        /// </summary>
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a UserName and Password to Proceed.
        /// </summary>
        internal static string MissingCredentials {
            get {
                return ResourceManager.GetString("MissingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        internal static string MsgSending {
            get {
                return ResourceManager.GetString("MsgSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Specify a Report to Generate.
        /// </summary>
        internal static string Report1 {
            get {
                return ResourceManager.GetString("Report1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Specify a Start and End Date to Proceed.
        /// </summary>
        internal static string Report2 {
            get {
                return ResourceManager.GetString("Report2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendMsg {
            get {
                return ResourceManager.GetString("SendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Specify the Message to be sent.
        /// </summary>
        internal static string SMSBlankMsg {
            get {
                return ResourceManager.GetString("SMSBlankMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Specify the Message to be saved .
        /// </summary>
        internal static string SMSBlankMsgSetting {
            get {
                return ResourceManager.GetString("SMSBlankMsgSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check Your Internet Connectivity to Proceed.
        /// </summary>
        internal static string SMSInternetIssue {
            get {
                return ResourceManager.GetString("SMSInternetIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Country Code Please Under Settings.
        /// </summary>
        internal static string SMSMissingCountryCode {
            get {
                return ResourceManager.GetString("SMSMissingCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a connected modem/phone to proceed.
        /// </summary>
        internal static string SMSModemNotSelected {
            get {
                return ResourceManager.GetString("SMSModemNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Specify the Category .
        /// </summary>
        internal static string SMSNoCategory {
            get {
                return ResourceManager.GetString("SMSNoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no recipients in the list.
        /// </summary>
        internal static string SMSNoRecipients {
            get {
                return ResourceManager.GetString("SMSNoRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Specify the Subcategory.
        /// </summary>
        internal static string SMSNoSubCategory {
            get {
                return ResourceManager.GetString("SMSNoSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Version Change Has Been Detected. The IQTools Database Will Be Updated.
        /// </summary>
        internal static string UpdateDatabase {
            get {
                return ResourceManager.GetString("UpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View The Report.
        /// </summary>
        internal static string ViewReport {
            get {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }
    }
}
